apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
    description: WAN github-backup
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: github-backup
    location: wan
  name: github-backup
  selfLink: /apis/extensions/v1beta1/namespaces/lan/deployments/github-backup
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: github-backup
      location: wan
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        description: WAN github-backup
      creationTimestamp: null
      labels:
        k8s-app: github-backup
        location: wan
      name: github-backup
    spec:
      containers:
      - env:
        - name: tz
          value: Europe/Berlin
        - name: GITHUB_USER
          value: INSERT_USERNAME
        - name: TOKEN
          value: INSERT_TOKEN
        image: marvinmarvin/docker-k8s-github-backup
        imagePullPolicy: Always
        name: github-backup
        volumeMounts:
        - mountPath: /etc/cron.d
          name: k8s-cfg-github-backup
        - mountPath: /root/.config/rclone
          name: k8s-cfg-github-backup
        resources: {}
        securityContext:
          privileged: false
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumes:
      - name: k8s-cfg-github-backup
        hostPath:
          path: /root/k8s-cfg/github-backup
          type: Directory
      dnsPolicy: ClusterFirst
      hostNetwork: false
      nodeSelector:
        location: wan
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
